services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  postgres-todo:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${TODO_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo-db-data:/var/lib/postgresql/data

  postgres-person:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PERSON_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - person-db-data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - todo-service
      - person-service
    environment:
      TODO_SERVICE_URL: ${TODO_SERVICE_URL}
      PERSON_SERVICE_URL: ${PERSON_SERVICE_URL}
  
  todo-service:
    build:
      context: .
      dockerfile: Dockerfile.todo-service
    ports:
      - ${TODO_SERVICE_PORT}:${TODO_SERVICE_PORT}
    depends_on:
      - postgres-todo
      - kafka
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-todo:5432/${TODO_DB}?schema=public"
      KAFKA_BROKER: ${KAFKA_BROKER}
  
  person-service:
    build:
      context: .
      dockerfile: Dockerfile.person-service
    ports:
      - ${PERSON_SERVICE_PORT}:${PERSON_SERVICE_PORT}
    depends_on:
      - postgres-person
      - kafka
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-person:5432/persons_db?schema=public"
      KAFKA_BROKER: ${KAFKA_BROKER}
  
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.notification-service
    ports:
      - ${NOTIFICATION_HTTP_PORT}:${NOTIFICATION_HTTP_PORT} # Port HTTP
      - ${NOTIFICATION_WS_PORT}:3004  # Port WebSocket
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      WS_PORT: 3004
  
volumes:
  todo-db-data:
  person-db-data: